### PR TITLE
Add contribute.json file.

### PR DESCRIPTION
**Pull request by Osmose**
Add a contribute.json file a la http://contribute.paas.allizom.org/.

### CODE REVIEW

**Comment by Osmose** [comment]
@erikrose r?

**Comment by erikrose** [comment]
Hmm. Right now, 5 of the 8 root-level files in peep are in the category of "rarely interesting tooling config". This would bump that ratio up even higher. What kind of ROI do you think we could expect in return?

You know what would be really cool? Having whatever you're using to index these files also understand (most non-ridiculously-dynamic) setup.py files, which already contain this information. I think the value comes from the index site, not the file format.

**Comment by Osmose** [comment]
Nunjucks said the same thing. :\

So http://mozilla.github.io/webdev/ is the thing that's pulling from these files. It uses the description from contribute.json (and falls back to the one in Github if it can't find that), but the two main unique things it uses that don't fit in setup.py are the link to the contribution homepage (big green button) and the keywords (PyPI keywords don't really fit there). I've also played around with having a detailed view of each project on there that pulls bugs from the bug list. 

Granted, this doesn't apply to peep since it doesn't really have anything compelling for either of these (except maybe a python keyword), but my point is that there's very little useful info that setup.py provides that I don't already know by the time I'm pulling the setup.py file automatically, and the info that it does provide doesn't change often enough to matter.

You're fine to not merge this if you don't think the added features on that indexing page are worth the extra file in your repo.

**Comment by erikrose** [comment]
I think I'll forgo it for peep for now. It doesn't keep it from being listed entirely, it doesn't have a contribution page to point to, and I'm not really seeking to grow the project anyway—really, I hope to merge it with pip and retire it within the year.

Btw, I love your live search on mozilla.github.io: so responsive!

I wonder if anybody has tried to institute a standard place to put these ever-multiplying tooling support files. I'd love to throw them all into a "tooling" folder, freeing up the root for project-relevant things. Then it wouldn't matter how many there were.

**Pull request closed without merging**
