### PR TITLE
don't allow duplicate names

### PR DESCRIPTION
**Pull request by andymckay**
it sucks when you've got duplicate modules in a requirements file, this stops peep from trying to do anything with them

### CODE REVIEW

**Comment by edmorley** [comment]
This is failing Travis since `Counter` is not available on Python 2.6.
IMO we should just drop support for Python 2.6 - it's time for people to move on (and if they don't wish to, they can just use previous peep release versions).

**Comment by andymckay** [comment]
Removed Counter, damn you python 2.6 :)

**Comment by edmorley** [comment]
As of #3372 (not yet released), pip no longer complains if there are duplicated requirements, so long as each has the same version specifier. Given this new behaviour, does this approach still make sense? :-)

**Comment by erikrose** [comment]
@edmorley No, probably not; we shouldn't needlessly differ from pip behavior. I'm closing this in favor of using the pip >8 that includes https://github.com/pypa/pip/pull/3372, when it's released. Reopen if you feel strongly.

**Pull request closed without merging**
